### ISSUE TITLE
API 2.0

### ISSUE THREAD

**Issue by ai** [aventrix/jnanoid#2]
Let’s update the library to be compatible with the latest Nano ID 2.0:

- [ ] Replace `~` to `-` in default alphabet
- [ ] Add `non-secure` fast generator
- [ ] Async API?

**Comment by davidklebanoff** [comment]
Hi @ai,
No problem, will update the default alphabet to match Nano ID 2.0. Any insight on the decision to change?

As for the non-secure generator, it is my understanding that it was added to the Javascript version was to offer better support for web workers. Being a Java library, we of course don't have the same need. On the current version of the library we provide two methods for developers to call, one with default settings and another that allows easy customization, similar to the `format` module in the Javascript version. If users want to use a non-secure random generator they can pass a Java [`Random`](https://docs.oracle.com/javase/7/docs/api/java/util/Random.html) object into that method and achieve the desired result. So, in an effort to keep the utility simple and clean, I think it may be best to forgo adding a new method to generate non-secure numbers and I'll simply add an example to the docs to achieve the same effect using the existing functionality.

I haven't put much consideration into async functionality at this time, but my instinct is to let developers control/implement the asynchronous functionionality as they desire. Especially given the changes in asynchronous support across Java 7 and Java 8. We are currently compiling to Java 7.

**Comment by ai** [comment]
> Any insight on the decision to change?

We used `~` instead of `-` because we tried to fix the old Android problem with a trailing `-` in links. Unfortunately, it didn’t help.

But `~` can be used as the first character of the file name. Also, the most solutions right now use `-` and they required `~` → `-` conversion during an update to Nano ID.

And small extra feature, with `-` JS code became more compact after gzip (since `-` is often used in JS)

**Comment by ai** [comment]
> Being a Java library, we of course don't have the same need.

You may need it for different reason. It is much faster. And there are a lot of cases, where you don’t need really random ID.

> Especially given the changes in asynchronous support across Java 7 and Java 8. We are currently compiling to Java 7.

Async code is required only if language really support it well. If it is rarely used or is not important for the users, you can miss it.
